version: '3'
networks:
  default:
    name: boilerplate_authentication_network
services:
  boilerplate_authentication_postgres:
    hostname: boilerplate_authentication_postgres
    container_name: boilerplate_authentication_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: boilerplate_authentication
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - default
  boilerplate_authentication_pgadmin:
    container_name: boilerplate_authentication_pgadmin
    image: adminer:latest
    ports:
      - 5431:8080
    networks:
      - default
  boilerplate_authentication_redis:
    hostname: boilerplate_authentication_redis
    container_name: boilerplate_authentication_redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - default
  boilerplate_authentication_redis_commander:
    hostname: boilerplate_authentication_redis_commander
    container_name: boilerplate_authentication_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=localhost:boilerplate_authentication_redis:6379
    ports:
      - 6380:8081
    networks:
      - default
    depends_on:
      - boilerplate_authentication_redis
