version: '3'
networks:
  default:
    name: boilerplate_authentication_network
services:

  postgres:
    hostname: boilerplate_authentication_postgres
    container_name: boilerplate_authentication_postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: boilerplate_authentication
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    container_name: boilerplate_authentication_pgadmin
    image: adminer
    ports:
      - 5431:8080
    networks:
      - default

  redis:
    hostname: boilerplate_authentication_redis
    container_name: boilerplate_authentication_redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - default

  redis-commander:
    container_name: boilerplate_authentication_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
